import { useEffect, useRef } from 'react'
import * as THREE from 'three'
import './Home.css'

function Hero3D(){const ref=useRef(null);useEffect(()=>{const c=ref.current;const r=new THREE.WebGLRenderer({canvas:c,antialias:true,alpha:true});const s=new THREE.Scene();const cam=new THREE.PerspectiveCamera(50,c.clientWidth/c.clientHeight,.1,100);cam.position.set(0,0,5);r.setSize(c.clientWidth,c.clientHeight);r.setPixelRatio(Math.min(devicePixelRatio,2));s.add(new THREE.AmbientLight(0xffffff,.7));const l=new THREE.DirectionalLight(0xffffff,.8);l.position.set(2,3,4);s.add(l);const body=new THREE.Mesh(new THREE.TorusKnotGeometry(1.1,.26,180,20),new THREE.MeshPhysicalMaterial({color:0xcdd5de,metalness:1,roughness:.18,clearcoat:1}));s.add(body);let id;const loop=()=>{id=requestAnimationFrame(loop);body.rotation.x+=.004;body.rotation.y+=.005;r.render(s,cam)};loop();const rs=()=>{r.setSize(c.clientWidth,c.clientHeight);cam.aspect=c.clientWidth/c.clientHeight;cam.updateProjectionMatrix()};window.addEventListener('resize',rs);return()=>{cancelAnimationFrame(id);window.removeEventListener('resize',rs);r.dispose()}},[]);return <canvas ref={ref} className='hero-canvas'/>}

export default function Home(){return <main className='tourbillon-style'>
<section id='hero' className='stage'><div className='overlay'/><div className='container stage-inner'><p className='micro'>GREENLOOP · NOUVELLE ÈRE</p><h1>Le composteur urbain, réinventé comme une expérience d’exception.</h1><p>GreenLoop simplifie le dépôt des déchets organiques en ville grâce à un composteur autonome, une identification par QR code et une application mobile claire.</p><div className='cta'><a href='#conception' className='solid'>Découvrir l'application</a><a href='#vision' className='line'>Voir la vision du projet</a></div></div><Hero3D/></section>
<section id='conception' className='panel container'><div className='left'><p className='micro'>CONCEPTION & APPLICATION</p><h2>Une technologie pensée pour durer.</h2><p>Accès sécurisé, pesée automatique, cuves multiples et autonomie énergétique: chaque élément sert un usage simple et immédiat.</p></div><iframe src='https://composte-urabain.vercel.app' title='Application GreenLoop'/></section>
<section id='vision' className='band'><div className='container'><p className='micro'>VISION ÉCOLOGIQUE</p><h2>Transformer le biodéchet urbain en ressource locale.</h2><div className='stats'><article><strong>30%</strong><span>des déchets ménagers sont compostables.</span></article><article><strong>150–200 kg</strong><span>de biodéchets produits par foyer et par an.</span></article><article><strong>Impact local</strong><span>Production d'engrais naturel, réduction des transports.</span></article></div></div></section>
<section id='equipe' className='panel container thin'><p className='micro'>ÉQUIPE & PARTENAIRES</p><h2>Cinq élèves, un projet, une ambition commune.</h2><div className='names'>{['Lucien Bisiaux','Louis Giraudel','Eliot Farys','Théophile Berenger','Clément Hintzy'].map(n=><span key={n}>{n}</span>)}</div></section>
<section id='modeles' className='panel container thin'><p className='micro'>MODÈLES 3D</p><h2>Explorer la conception du prototype.</h2><p>Structure principale · 4 cuves de compostage · Système de pesée · Module électronique · Alimentation solaire · Trappe sécurisée.</p></section>
</main>}
